### ISSUE TITLE
Crash when updating head

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#1231]
```
INF 2020-06-24 20:14:37+02:00 Updated head block (new parent)            topics="hotdb" tid=181528 file=candidate_chains.nim:750 cat=fork_choice finalizedEpoch=6466 headBlock=4babf5f0:207071 headParent=adfeacd7:207070 justifiedEpoch=6468 lastHead=107cd986:207072 pcs=fork_choice stateRoot=990577b8 stateSlot=207071
 peers: 10 ❯ finalized: 1ad01e1d:6468 ❯ head: 107cd986:6471:0 ❯ time: 6471:1 (207073)                                                                                                                     ETH: 30.275957251 
Thread 1 "beacon_node_sha" received signal SIGSEGV, Segmentation fault.
updateHead__AJLkY89a9aGB863wo7MSQplQ (dag=<optimized out>, newHead=newHead@entry=0x7fffd98299a8) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/block_pools/candidate_chains.nim:809
809	          for child in cur.parent.children:
Missing separate debuginfos, use: dnf debuginfo-install nss-mdns-0.14.1-7.fc32.x86_64
(gdb) bt full
#0  updateHead__AJLkY89a9aGB863wo7MSQplQ (dag=<optimized out>, newHead=newHead@entry=0x7fffd98299a8) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/block_pools/candidate_chains.nim:809
        cur = 0x0
        T106_ = <optimized out>
        hlen_1 = <optimized out>
        T130_ = <optimized out>
        TM__Jvo3E39chhFUVIjpSubE9arw_158 = {prev = 0xe9cf3860c9640a4, status = -6953433133401774977, context = {{__jmpbuf = {-8994064513804752258, 32000000000, 0, 4957, 4966, -1, -1, 0}, __mask_was_saved = 0, 
              __saved_mask = {__val = {18446744073709549840, 140737223832168, 140737223832168, 140737193380552, 140737223831624, 18446744073709549840, 11744278, 140736825016392, 207008, 140737488330368, 17742117, 462, 
                  17914280, 524288, 0, 140737488330240}}}}}
        _nimCurFrame = <optimized out>
        lastHead = <optimized out>
        T31_ = <optimized out>
        justifiedSlot = <optimized out>
        justifiedBS = {blck = 0x7fffd87e4598, slot = 206976}
        T32_ = <optimized out>
        finalizedEpochStartSlot = <optimized out>
        finalizedHead = {blck = 0x7fffe61a1c28, slot = 206912}
        FR_ = {prev = 0x7fffffff9eb0, procname = 0x10eb324 "updateHead", line = 819, filename = 0x11141f8 "/home/arnetheduck/status/nim-beacon-chain/beacon_chain/block_pools/candidate_chains.nim", len = 0, 
          calldepth = 9, frameMsgLen = 288230376151711743}
#1  0x0000000000fffc61 in updateHead__nyQ09byxBYXcuj6ahRfs8aQblock_pool (newHead=0x7fffd98299a8, pool=0x7ffff03bb238) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/block_pool.nim:124
        FR_ = {prev = 0x7fffffff9e80, procname = 0x10eb324 "updateHead", line = 123, filename = 0x11159f8 "/home/arnetheduck/status/nim-beacon-chain/beacon_chain/block_pool.nim", len = 0, calldepth = 8, 
          frameMsgLen = 140737193380464}
        FR_ = <optimized out>
#2  updateHead__O5kQNbon5A0VwQtonLjtWA (node=0x7ffff03bb048) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node_common.nim:68
        result = 0x0
        newHead = 0x7fffd98299a8
        T1_ = <optimized out>
        T2_ = <optimized out>
        FR_ = {prev = 0x7fffffff9f50, procname = 0x10eb324 "updateHead", line = 68, filename = 0x1120248 "/home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node_common.nim", len = 0, calldepth = 7, 
          frameMsgLen = 9059902}
#3  0x00000000010ae75d in onSlotStart__LOpexeSSOxNbrTjyAhR0Ug_26 (ClE_0=<optimized out>) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim:470
        T158_ = <optimized out>
        T200_ = <optimized out>
        TM__EQx9bQP0TE2iLmLbmLjJEIw_522 = {prev = 0x7fffffffa5f0, status = 0, context = {{__jmpbuf = {140737193380464, -6680510994865357830, -1776, 140737488331936, 140737223831624, -1776, -6680510993953096710, 
                6680513145599917050}, __mask_was_saved = 0, __saved_mask = {__val = {17587248, 140737488331420, 17587280, 0, 0, 0, 0, 0, 140737488331080, 0, 0, 0, 0, 0, 0, 0}}}}}
        T119_ = 0x0
        T159_ = <optimized out>
        T160_ = <optimized out>
        TM__EQx9bQP0TE2iLmLbmLjJEIw_545 = {prev = 0x0, status = 0, context = {{__jmpbuf = {0, 140737351759964, 0, 140737351760949, 0, 140737351759904, 4611686018427387904, 140737488331312}, __mask_was_saved = 19434052, 
              __saved_mask = {__val = {140737351764945, 0, 0, 18754064, 12029, 40, 0, 514, 0, 19419288, 3, 0, 140737488331168, 14, 5785798, 140737488331232}}}}}
        T199_ = <optimized out>
        result = <optimized out>
        colonenvP_ = <optimized out>
        _nimCurFrame = <optimized out>
        FR_ = {prev = 0x7fffffffa710, procname = 0x10dcde0 "onSlotStart", line = 469, filename = 0x11152b8 "/home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim", len = 0, calldepth = 6, 
--Type <RET> for more, q to quit, c to continue without paging--
          6148992}
#4  0x0000000001080abd in onSlotStart_continue__22tHtKSiA9bvHMF1A03cXvg (udataX60gensym311535217_=udataX60gensym311535217_@entry=0x0, ClE_0=ClE_0@entry=0x7fffd8c32d68)
    at /home/arnetheduck/status/nim-beacon-chain/vendor/nim-chronos/chronos/asyncmacro2.nim:36
        T4_ = <optimized out>
        nextX60gensym311535218_ = 0x7ffff7bb6788
        colonenvP_ = <optimized out>
        TM__EQx9bQP0TE2iLmLbmLjJEIw_548 = {prev = 0x7fffffffaae0, status = 0, context = {{__jmpbuf = {140736830057832, -6680477015822992390, -1776, 207073, 140737223831624, -1776, -6680510994850677766, 6680513123529620474}, __mask_was_saved = 0, 
              __saved_mask = {__val = {17672684, 241, 17860264, 393216, 17860264, 140737488332352, 17672692, 184, 17860264, 458752, 17859936, 140737488332400, 17672699, 430, 17859936, 140733193912320}}}}}
        _nimCurFrame = <optimized out>
#5  0x000000000108169d in onSlotStart__6cKhm9c9ag9bcBKH9cqGodAmdA (scheduledSlot=207073, lastSlot=<optimized out>, node=0x7ffff03bb048) at /home/arnetheduck/status/nim-beacon-chain/vendor/nim-chronos/chronos/asyncmacro2.nim:63
        colonenv_ = 0x7fffd8c32d68
        colonenv__2 = 0x7fffee6b0a70
        T2_ = <optimized out>
        result = 0x0
        T1_ = <optimized out>
        T3_ = <optimized out>
        result = <optimized out>
        colonenv_ = <optimized out>
        T1_ = <optimized out>
        colonenv__2 = <optimized out>
        T2_ = <optimized out>
        T3_ = <optimized out>
#6  colonanonymous___E9cgD8am2ENbraSha1WG31A_4 (p_0=<optimized out>, ClE_0=<optimized out>) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim:503
        colonenvP_ = <optimized out>
        T1_ = 0x0
        FR_ = {prev = 0x7fffffffa7a0, procname = 0x10e0cc4 ":anonymous", line = 503, filename = 0x11152b8 "/home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim", len = 0, calldepth = 5, frameMsgLen = 17674465}
#7  0x00000000006c674a in poll__YNjd8fE6xG8CRNwfLnrx0g_2 () at /home/arnetheduck/status/nim-beacon-chain/vendor/nim-chronos/chronos/asyncloop.nim:279
        callableX60gensym19250819_ = {function = {ClP_0 = 0x1081580 <colonanonymous___E9cgD8am2ENbraSha1WG31A_4>, ClE_0 = 0x7fffee6b0868}, udata = 0x0, deleted = 0 '\000'}
        TM__xRflM5lMv4YvZq7gOUBMew_31 = <optimized out>
        iX60gensym19250818_ = 0
        i_4 = 0
        loop = 0x7ffff7b7e9a0
        curTime = <optimized out>
        curTimeout = <optimized out>
        customSet = 60
        lastFinishX60gensym19165207_ = <optimized out>
        count = <optimized out>
        curTimeX60gensym19240038_ = <optimized out>
        countX60gensym19250817_ = 1
        FR_ = {prev = 0x7fffffffa8d0, procname = 0x10ddd87 "poll", line = 278, filename = 0x110c878 "/home/arnetheduck/status/nim-beacon-chain/vendor/nim-chronos/chronos/asyncloop.nim", len = 0, calldepth = 4, frameMsgLen = 5803050}
#8  0x00000000010b2acc in run__2mtcMOB7G7Y9akxH5O2MOqg_3 (node=node@entry=0x7ffff03bb048) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim:824
        TM__EQx9bQP0TE2iLmLbmLjJEIw_639 = {prev = 0x0, status = 0, context = {{__jmpbuf = {140737232530568, -6680474437779358726, 140737349533784, 0, 140737349205576, 0, -6680510994450121734, 6680513131025366010}, __mask_was_saved = 0, __saved_mask = {
                __val = {140737488333656, 140737488333880, 5791013, 126, 140737488333656, 140737488333792, 17673457, 140737488333760, 17686042, 405, 17877024, 140733193715712, 5800657, 0, 18446744073709549840, 140737209676856}}}}}
        colonenv_ = 0x7ffff7b4be48
        _nimCurFrame = 0x7fffffffa8d0
        FR_ = {prev = 0x7fffffffad10, procname = 0x10dd323 "run", line = 823, filename = 0x11152b8 "/home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim", len = 0, calldepth = 3, frameMsgLen = 17682999}
#9  0x00000000010b333b in start__2mtcMOB7G7Y9akxH5O2MOqg_2 (node=node@entry=0x7ffff03bb048) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim:874
        head_1 = <optimized out>
        finalizedHead = <optimized out>
        genesisTime = <optimized out>
        T1_ = <optimized out>
        T2_ = <optimized out>
        _nimCurFrame = <optimized out>
        TM__EQx9bQP0TE2iLmLbmLjJEIw_209 = {prev = 0x0, status = 0, context = {{__jmpbuf = {-1776, -6680510991149204486, 140737349533784, 0, 140737223831624, 0, -6680510994599019526, 6680513130191092730}, __mask_was_saved = 0, __saved_mask = {__val = {
                  19847616, 5838896, 44070, 181, 72057594055788304, 262144, 17859936, 327680, 19847640, 140737349585848, 5803050, 140737488335088, 1638990646510276096, 260, 140737349585752, 19847616}}}}}
        T61_ = <optimized out>
        FR_ = {prev = 0x7fffffffb4d0, procname = 0x10dda73 "start", line = 873, filename = 0x11152b8 "/home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim", len = 0, calldepth = 2, frameMsgLen = 17672743}
#10 0x00000000010b7670 in main__kYRn29bPOsjfiAecYiv9b2ng () at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim:1137
        TM__EQx9bQP0TE2iLmLbmLjJEIw_54 = {prev = 0x0, status = 0, context = {{__jmpbuf = {140737349533768, -6680510991149204486, 140737349537864, 0, 0, 0, -6680510995219776518, 6680513132824853498}, __mask_was_saved = 0, __saved_mask = {__val = {
                  140737488340800, 140737354130600, 140737353987676, 2780106507, 1, 140737349685964, 4196608, 5, 140737353988708, 160, 140737349751600, 140737351540736, 140737488339592, 140737488339588, 140737351542592, 140737354129728}}}}}
        T229_ = <optimized out>
        node = <optimized out>
        T230_ = <optimized out>
        colonenv_ = <optimized out>
        bannerX60gensym332900005_ = <optimized out>
        T1_ = <optimized out>
        T2_ = <optimized out>
        _nimCurFrame = 0x7fffffffb4d0
        FR_ = {prev = 0x7fffffffcbc0, procname = 0x10d76db "main", line = 1136, filename = 0x11152b8 "/home/arnetheduck/status/nim-beacon-chain/beacon_chain/beacon_node.nim", len = 0, calldepth = 1, frameMsgLen = 0}
#11 0x00000000010be247 in NimMainModule () at /home/arnetheduck/status/nim-beacon-chain/vendor/nim-testutils/testutils/moduletests.nim:22
        T2_ = 0x0
        T4_ = 0x0
        FR_ = {prev = 0x0, procname = 0x10f9c7e "beacon_node", line = 21, filename = 0x11219a8 "/home/arnetheduck/status/nim-beacon-chain/vendor/nim-testutils/testutils/moduletests.nim", len = 0, calldepth = 0, frameMsgLen = 17259584}
        T1_ = 0x0
        T3_ = 0x0
        T5_ = 0x0
#12 0x00000000010c5c13 in NimMain () at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/mainchain_monitor.nim:514
        inner = 0x10be290 <NimMainInner>
#13 0x000000000040437d in main (argc=<optimized out>, args=<optimized out>, env=<optimized out>) at /home/arnetheduck/status/nim-beacon-chain/beacon_chain/mainchain_monitor.nim:521
No locals.
```

**Comment by arnetheduck** [comment]
obsolete
