### ISSUE TITLE
OOM on 2gb VM when running beacon node

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-beacon-chain#246]
```
#0  raiseOutOfMem_II46IjNZztN9bmbxUD8dt8g () at nimcache/release/beacon_node/stdlib_system.c:2535
No locals.
#1  0x0000555555591ac4 in osAllocPages_fxkHg9ajpjxOfBTuIyrgEfwsystem (size=2121772718) at nimcache/release/beacon_node/stdlib_system.c:2555
        T3_ = <optimized out>
        result = 0xffffffffffffffff
        result = <optimized out>
        T3_ = <optimized out>
#2  getHugeChunk_z9bCNjXTYllZ3pI24nEsw2g_3 (size=2121772718, a=0x7ffff6b44a90) at nimcache/release/beacon_node/stdlib_system.c:3067
        result = 0x0
        T1_ = 0x0
        T2_ = <optimized out>
        T3_ = <optimized out>
        result = <optimized out>
        T1_ = <optimized out>
        T2_ = <optimized out>
        T3_ = <optimized out>
#3  rawAlloc_yn9c8RLaS8vgVBeMBfmkdUg (a=0x7ffff6b44a90, requestedSize=2121772686) at nimcache/release/beacon_node/stdlib_system.c:3231
        c_2 = <optimized out>
        result = 0x0
        size = 2121772718
#4  0x00005555555957e4 in rawNewObj_BpNS5yt3b9cMOponsUKh8aw (typ=0x555555883740 <strDesc_D0UzA4zsDu5tgpJQ9a9clXPg>, size=2121772670, gch=0x7ffff6b44a30) at nimcache/release/beacon_node/stdlib_system.c:5260
        result = 0x0
        res = <optimized out>
        T1_ = 0x0
#5  0x0000555555596ef6 in newObj (size=2121772670, typ=0x555555883740 <strDesc_D0UzA4zsDu5tgpJQ9a9clXPg>) at nimcache/release/beacon_node/stdlib_system.c:5338
        result = 0x0
        result = <optimized out>
#6  rawNewString (space=<optimized out>) at nimcache/release/beacon_node/stdlib_system.c:6109
        result = 0x0
        s = 2121772653
        T5_ = 0x0
#7  0x000055555561b787 in setProperty_zr9cbCQ6OY18NKqEzwfOntg (r=r@entry=0x7fffecba6888, key=key@entry=0x5555556fe920 <TM_CXCLsJEpGv9b1vOuVf9b8WPg_145>, val=<optimized out>) at nimcache/release/beacon_node/chronicles_log_output.c:1444
        T5_ = <optimized out>
        valText = 0x7fffecce6030
        escaped = 0x0
        valueToWrite = 0x0
        needsEscape = 0 '\000'
        T1_ = -1
        needsQuote = 1 '\001'
        T2_ = 67
        T17_ = <optimized out>
        color = <optimized out>
        bright = <optimized out>
        T26_ = <optimized out>
        T27_ = <optimized out>
#8  0x00005555556ce7c3 in BeaconSyncHandshakeIter_xwYwX59aN9bWD9b7yCXh9bY9a9cQ_12 (ClE_0=<optimized out>) at nimcache/release/beacon_node/beacon_chain_sync_protocol.c:5641
        T114_ = <optimized out>
        T5_ = <optimized out>
        T22_ = <optimized out>
        T117_ = {blockBodies = 0x2}
        T6_ = <optimized out>
        T23_ = <optimized out>
        T100_ = <optimized out>
        T115_ = <optimized out>
        T4_ = <optimized out>
        T7_ = <optimized out>
        T99_ = <optimized out>
        T101_ = <optimized out>
        T116_ = {blockHeaders = 0x28bbaa65}
        TM_CXCLsJEpGv9b1vOuVf9b8WPg_128 = {prev = 0x7fffffffd580, status = 0, context = {{__jmpbuf = {140737163911216, 3159923515159238156, 0, 7, 0, 140737488344816, 3159923514706253324, 9119534811047810572}, __mask_was_saved = 0, __saved_mask = {__val = {6012625239, 2, 
                  36966597315853299, 17181397764423729, 240155688582375068, 98121787487212078, 10090228593657407, 217893894043528827, 1795477884, 1, 13046229738931364, 260222513921184480, 23520397333292662, 255055265916844673, 158894572568973243, 1377847022073132}}}}, 
          hasRaiseAction = 0 '\000', raiseAction = {ClP_0 = 0x2, ClE_0 = 0x17400d203a9fb84}}
        result = <optimized out>
        colonenvP_ = <optimized out>
#9  0x00005555556cb073 in BeaconSyncHandshake_continue_vzwoY1g5GGqNXbnwrMwF5w_12 (udata=<optimized out>, ClE_0=<optimized out>) at nimcache/release/beacon_node/beacon_chain_sync_protocol.c:5716
        T4_ = <optimized out>
        next = 0x0
        colonenvP_ = <optimized out>
        TM_CXCLsJEpGv9b1vOuVf9b8WPg_154 = {prev = 0x0, status = 0, context = {{__jmpbuf = {140737331925064, 3159923515159238156, 0, 7, 140737488344808, 140737488344816, 3159923515075352076, 9119534807856993804}, __mask_was_saved = 0, __saved_mask = {__val = {0, 0, 0, 0, 
                  0, 140737488344576, 17661373760609361920, 0, 93824992487537, 140737331942552, 93824994264496, 140737331942552, 93824992488128, 140737488344800, 93824994264400, 140737331942552}}}}, hasRaiseAction = 0 '\000', raiseAction = {ClP_0 = 0x3, 
            ClE_0 = 0x555555592ac0 <genericResetAux_ruA1rosalqf8AhzZPPTBQg+80>}}
        T4_ = <optimized out>
        next = <optimized out>
        T9_ = <optimized out>
        T13_ = <optimized out>
        T22_ = <optimized out>
        msg = <optimized out>
        e = <optimized out>
        T26_ = <optimized out>
        T31_ = <optimized out>
        T35_ = <optimized out>
#10 0x00005555555ffd5a in poll_yNXn6B3diVrj9apUe0xlOKQ_3 () at nimcache/release/beacon_node/chronos_asyncloop.c:1569
        callable = {function = {ClP_0 = 0x5555556cb000 <BeaconSyncHandshake_continue_vzwoY1g5GGqNXbnwrMwF5w_12>, ClE_0 = 0x7ffff6addd08}, udata = 0x0, deleted = 0 '\000'}
        i_3 = 0
        i_4 = 0
        loop = 0x7ffff6ad1048
        curTime = <optimized out>
        curTimeout = <optimized out>
        count = <optimized out>
        count_2 = <optimized out>
        curTime_2 = <optimized out>
        count_3 = <optimized out>
        count_4 = 7
#11 0x00005555555fff95 in waitFor_tm1B9avdJxPkCFV1gicMhvA (fut=0x7ffff6ad10a0) at nimcache/release/beacon_node/chronos_asyncloop.c:1641
        T3_ = <optimized out>
#12 0x0000555555589b11 in start_z9cTQGJZIUBDf5AuLHSWtNQ (node=0x7fffeed7a030, headState=0x7fffeed7a218) at nimcache/release/beacon_node/beacon_chain_beacon_node.c:7768
        T1_ = <optimized out>
#13 0x000055555558ca58 in NimMainModule () at nimcache/release/beacon_node/beacon_chain_beacon_node.c:8734
        T67_ = <optimized out>
        T68_ = <optimized out>
        T1_ = 0x0
        T2_ = <optimized out>
        T3_ = {logLevel = 2 '\002', network = 0x7ffff6aec438, dataDir = 0x7ffff6aeb1f8, cmd = 0 '\000', _Ucmd = {S1 = {bootstrapNodes = 0x0, bootstrapNodesFile = 0x0, tcpPort = 9000, udpPort = 9000, nat = 0x7ffff6ad8fe8, validators = 0x0, stateSnapshot = {val = 0x0, 
                has = 0 '\000'}, nodename = 0x0}, S2 = {networkId = 0, validatorsDir = 0x0, totalValidators = 9000, firstValidator = 9000, lastUserValidator = 140737331957736, bootstrapAddress = 0x0, bootstrapPort = 0, genesisOffset = 0, outputGenesis = 0x0, 
              outputNetwork = 0x0}, S3 = {keyFiles = 0x0}}}
#14 0x000055555558bb53 in NimMain () at nimcache/release/beacon_node/beacon_chain_beacon_node.c:8421
        inner = 0x55555558ca70 <NimMainInner>
#15 0x000055555555873d in main (argc=<optimized out>, args=<optimized out>, env=<optimized out>) at nimcache/release/beacon_node/beacon_chain_beacon_node.c:8428
No locals.
quit
```

**Comment by arnetheduck** [comment]
7655b7d4b26a26391d77db0d3549f81fa4bd1d1b

**Comment by arnetheduck** [comment]
obsolete
