### ISSUE TITLE
Nimbus Besu connection disruption

### ISSUE THREAD

**Issue by yorickdowne** [status-im/nim-beacon-chain#4773]
**Describe the bug**

Nimbus 23.3.2 with Besu 23.1.2, the Engine API connection gets disrupted. Reported on Discord; I think I can reproduce this. Fresh Nimbus/Besu sync on Goerli, with Nimbus checkpoint synced and Besu snap synced.

**Additional context**

Debug logs are too large to attach, placed them on dropbox: https://www.dropbox.com/s/69sejeefa9i85kt/nimbus-besu-connection-woes.debug.log.tar.gz?dl=0

Log examples from Nimbus

```
consensus_1             | WRN 2023-03-29 20:25:07.252+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
consensus_1             | INF 2023-03-29 20:25:09.810+00:00 Connection to EL node restored             topics="elmon" url=http://execution:8551
```

and Besu
```
execution_1             | java.net.SocketException: Connection reset
execution_1             |     at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
execution_1             |     at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
execution_1             |     at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
execution_1             |     at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
execution_1             |     at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
execution_1             |     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
execution_1             |     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
execution_1             |     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
execution_1             |     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
execution_1             |     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
execution_1             |     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
execution_1             |     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
execution_1             |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
execution_1             |     at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by tersec** [comment]
```
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:29:48.792+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:29:56.709+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:31:10.918+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:31:19.027+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:33:16.300+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:33:24.321+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:33:41.901+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:33:49.518+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:34:06.498+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:34:14.649+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:34:30.810+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:34:38.711+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:34:56.486+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:35:03.909+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:36:17.203+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:36:25.194+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:38:23.295+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:38:31.204+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:39:44.817+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:39:52.696+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:40:51.392+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:40:59.392+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:42:42.640+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:42:50.686+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:44:03.751+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:44:11.709+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:44:13.838+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:44:21.836+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:44:53.600+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:45:01.589+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:45:31.898+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:45:39.819+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:48:32.592+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:48:40.142+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:49:25.616+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:49:33.022+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:51:30.729+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:51:38.730+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:52:51.425+00:00 Failed to obtain the latest block from the EL topics="elmon" err="{\"code\":-32603,\"message\":\"Internal error\"}" url=http://execution:8551
nimbus-besu-connection-woes.nimbus.debug.log:consensus_1             | WRN 2023-03-29 20:52:59.328+00:00 Connection to EL node degraded             topics="elmon" url=http://execution:8551 failedRequest=getBlockByNumber statusCode=0 err="{\"code\":-32603,\"message\":\"Internal error\"}"
```
That's 40 times in 23 minutes. Nimbus is simply reporting the internal error here. -32603 [is an engine API error code](https://github.com/ethereum/execution-apis/blob/main/src/engine/common.md#errors) which is defined for this purpose, but it's not a Nimbus error. Nimbus appears to be reacting appropriately to such errors.

**Comment by yorickdowne** [comment]
So, it's not that Nimbus is creating too many connections for Besu to  handle? You're saying this may need to be fixed on the Besu side?

**Comment by tersec** [comment]
It's possible Nimbus is creating multiple connections to Besu; the `http://execution:8551` in the Nimbus logs indicates it's using a protocol which is capable of creating multiple connections. Websocket has other issues, but it does tend to be more constrained to the single connection it opens.

But the `getBlockByNumber` call it mentions is part of Nimbus's deposit syncing/processing, which it has to do even if it checkpoint syncs. It can know the current state quickly that way, but to properly propose it also needs to know the deposits, which aren't included in the checkpointed state. So, it uses `getBlockByNumber` to scan blocks with beacon chain deposit contract transactions. This is what those logs are showing.

Notably, (a) this deposit processing code doesn't have any particularly notable tendency to create lots of extra connections, and (b) `getBlockByNumber` should be among the fastest nontrivial engine API calls. Regardless of potentially multiple HTTP JSON-RPC connections, Besu should not be throwing -32603. That's purely on Besu.

It's possible Nimbus does have some bugs evident in these logs, and it's interesting to see how it performs in such degraded conditions -- it's useful to have these kinds of non-happy-path logs, especially reproducible ones which indicate conditions it's plausibly likely to encounter on the network live. But the specific error you quote, indeed, looks to be on Besu.

**Comment by yorickdowne** [comment]
Closing this
