### ISSUE TITLE
[Windows] beaconnode createChain SIGSEGV

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#78]
beaconnode createChain crashes with a strange error related to Cygwin in the current master https://github.com/status-im/nim-beacon-chain/tree/dda24619e824ef78c216d8a99ee280e57f182aa8 compared to the master from  a week ago: https://github.com/status-im/nim-beacon-chain/tree/fix-sim-init-windows.

![image](https://user-images.githubusercontent.com/22738317/52052394-8167f600-2556-11e9-925e-c7d550dbc470.png)

Full backtrace with debugging symbol:

```
#0  __chkstk_ms () at ../../../../../src/gcc-4.9.1/libgcc/config/i386/cygwin.S:172
#1  0x0061b2aa in get_initial_beacon_state_vi9cRmmSUyyCGR9cJE84pqSw (initial_validator_deposits=0x5f2c3165, initial_validator_depositsLen_0=1887007839, genesis_time=6857984371532455724, latest_eth1_data=0x14cbaa8, flags=116 't', Result=0x14cbae8) at D:/Devel/Status/nim-beacon-chain/beacon_chain/spec/beaconstate.nim:159
#2  0x004a7f48 in createStateSnapshot_ahCWD5wcxfkrgWQSdv9cjfQ (startup=..., outFile=0x173a8e8) at D:/Devel/Status/nim-beacon-chain/beacon_chain/trusted_state_snapshots.nim:33
#3  0x00439e9d in NimMainModule () at D:/Devel/Status/nim-beacon-chain/beacon_chain/beacon_node.nim:402
#4  0x00439c11 in NimMainInner () at C:/Users/Beta/.choosenim/toolchains/nim-0.19.2/lib/system.nim:3404
#5  0x00439c35 in NimMain () at C:/Users/Beta/.choosenim/toolchains/nim-0.19.2/lib/system.nim:3412
#6  0x00439c5f in main (argc=4, args=0x1b914a8, env=0x1b91d98) at C:/Users/Beta/.choosenim/toolchains/nim-0.19.2/lib/system.nim:3419
```

Note that this is with 32-bit Nim

**Comment by mratsim** [comment]
Fixed by #248
